####################
# Constants
#
#See https://en.wikipedia.org/wiki/List_of_Unicode_characters
#http://www.cloford.com/resources/charcodes/utf-8_punctuation.htm
#http://xahlee.info/comp/unicode_matching_brackets.html
#Format is matching pattern, substitution, comment, language id
UTF8MAP = list(
    c("\u00A0"," ","Spaces: non-breaking space"),
    c("\ufeff"," ","Spaces: invisible"),
    c("\u200B"," ","Spaces: zero-width space"),
    c("\u200c"," ","Spaces: zero-width non-joiner"),
    c("\u200d"," ","Spaces: zero-width joiner"),
    c("\u2002"," ","Spaces: en space"),
    c("\u2003"," ","Spaces: em space"),
    c("\u2000"," ","Spaces: en quad"),
    c("\u2001"," ","Spaces: em quad"),
    c("\u2004"," ","Spaces: three-per-em space"),
    c("\u2005"," ","Spaces: four-per-em space"),
    c("\u2006"," ","Spaces: six-per-em space"),
    c("\u2007"," ","Spaces: figure space"),
    c("\u2008"," ","Spaces: punctuation space"),
    c("\u2009"," ","Spaces: thin space"),
    c("\u200A"," ","Spaces: hair space"),
    c("\u200e"," ","Spaces: left to right mark, narrow no-break space"),
    c("\u200f"," ","Spaces: right to left mark, narrow no-break space"),
    c("\u205f"," ","Spaces: math space"),
    c("\u3000"," ","Spaces: ideographic space"),
    c("\u060c",",","Comma: arabic comma"),
    c("\u066b",",","Comma: arabic decimal separator"),
    c("\u066c",",","Comma: arabic thousands separator"),
    c("\u3001",",","Comma: ideographic comma"),
    c("\ufe50",",","Comma: small comma"),
    c("\uff0c",",","Comma: fullwidth comma"),
    c("\u06d4",".","Full stop: arabic full stop"),
    c("\u2024",".","Full stop: one dot leader"),
    c("\ufe52",".","Full stop: small full stop"),
    c("\uff0e",".","Full stop: fullwidth full stop"),
    c("\u3002",".","Full stop: ideographic full stop"),
    c("\ufe55",":","Colon: small colon"),
    c("\uff1a",":","Colon: fullwidth colon"),
    c("\u0387",";","Semi colon: greek ano teleia"),
    c("\u061B",";","Semi colon: arabic semicolon"),
    c("\ufe54",";","Semi colon: small semicolon"),
    c("\uff1b",";","Semi colon: fullwidth semicolon"),
    c("\u2010","-","Hyphen: hyphen"),
    c("\u2011","-","Hyphen: non-breaking hyphen"),
    c("\u2012","-","Hyphen: figure dash"),
    c("\u2013","-","Hyphen: en dash"),
    c("\uff0d","-","Hyphen: fullwidth hyphen minus"),
    c("\u2014","-","Hyphen: em dash"),
    c("\u2015","-","Hyphen: horizontal bar "),
    c("\u2018","'","Quotation mark: left single quotation mark"),
    c("\u2019","'","Quotation mark: right single quotation mark"),
    c("\u201a","'","Quotation mark: single low-9 quotation mark"),
    c("\u201b","'","Quotation mark: single reversed-9 quotation mark"),
    c("\u201c","'","Quotation mark: left double quotation mark"),
    c("\u201d","'","Quotation mark: right double quotation mark"),
    c("\u201e","'","Quotation mark: double low-9 quotation mark"),
    c("\u2032","'","Quotation mark: prime"),
    c("\u2033","'","Quotation mark: double prime"),
    c("\u2034","'","Quotation mark: triple prime"),
    c("\u2035","'","Quotation mark: reversed prime"),
    c("\u2036","'","Quotation mark: reversed double prime"),
    c("\u2037","'","Quotation mark: reversed triple prime"),
    c("\u2039","'","Quotation mark: single left-pointing angle quotation mark"),
    c("\u203A","'","Quotation mark: single right-pointing angle quotation mark"),
    c("\u00b4","'","Quotation mark: acute accent"),
    c("\uff07","'","Quotation mark: fullwidth apostrophe"),
    c("\u00ab","\"","Quotation mark: left-pointing double angle quotation mark"),
    c("\u00bb","\"","Quotation mark: right-pointing double angle quotation mark"),
    c("\u037e","?","Question mark: greek question mark"),
    c("\u00bf","?","Question mark: inverted question mark"),
    c("\u061f","?","Question mark: arabic question mark"),
    c("\u203d","?","Question mark: interrobang combined question and exclamation marks"),
    c("\ufe56","?","Question mark: small question mark"),
    c("\uff1f","?","Question mark: fullwidth question mark"),
    c("\uff01","!","Exclamation mark: fullwidth exclamation mark"),
    c("\ufe6b","@","Commercial at: small commercial at"),
    c("\uff20","@","Commercial at: fullwidth commercial at"),
    c("\u2022"," ","Bullet: bullet"),
    c("\u2023"," ","Bullet: triangular bullet"),
    c("\u2025"," ","Dot leader: two dot leader"),
    c("\u2026"," ","Horizontal ellipsis:horizontal ellipsis"),
    c("\u2027"," ","Hyphenation: hyphenation point"),
    c("\u00BC","1/4","Number forms: un quart"),
    c("\u00BD","1/2","Number forms: un demi"),
    c("\u00BE","3/4","Number forms: trois quarts"),
    c("\u2153","1/3","Number forms: un tiers"),
    c("\u2154","2/3","Number forms: deux tiers"),
    c("\u2155","1/5","Number forms: un cinqieme"),
    c("\u2156","2/5","Number forms: deux cinqieme"),
    c("\u2157","3/5","Number forms: trois cinqieme"),
    c("\u2158","4/5","Number forms: quatre cinqieme"),
    c("\u2159","1/6","Number forms: un sixieme"),
    c("\u215A","5/6","Number forms: cinq sixieme"),
    c("\u215B","1/8","Number forms: un huitieme"),
    c("\u215C","3/8","Number forms: trois huitieme"),
    c("\u215D","5/8","Number forms: cinq huitieme"),
    c("\u215E","7/8","Number forms: sept huitieme"),
    c("\u0152","oe","Ligatures: lattin small ligature oe"),
    c("\u0153","oe","Ligatures: lattin small ligature oe"),
    c("\u2794","","HEAVY WIDE-HEADED RIGHTWARDS ARROW"),
    c("\u00A1","","INVERTED EXCLAMATION MARK"),
    c("\u00A9","","COPYRIGHT SIGN"),
    c("\u00AE","","REGISTERED SIGN"),
    c("\u00B7","","MIDDLE DOT"),
    c("\u00B1","","SUPERSCRIPT ONE"),
    c("\u00E0","a","LATIN SMALL LETTER A WITH GRAVE"),
    c("\u00E3","a","LATIN SMALL LETTER A WITH GRAVE"),
    c("\u00E5","a","LATIN SMALL LETTER A WITH GRAVE"),
    c("\u00E6","ae","LATIN SMALL LETTER AE"),
    c("\u00EC","i","LATIN SMALL LETTER I WITH GRAVE"),
    c("\u00ED","i","LATIN SMALL LETTER I WITH ACUTE"),
    c("\u00EF","i","LATIN SMALL LETTER I WITH DIAERESIS"),
    c("\u00F0","","LATIN SMALL LETTER ETH"),
    c("\u00F1","n","LATIN SMALL LETTER N WITH TILDE"),
    c("\u00F2","o","LATIN SMALL LETTER O WITH GRAVE"),
    c("\u00F3","o","LATIN SMALL LETTER O WITH GRAVE"),
    c("\u00F7","","DIVISION SIGN"),
    c("\u00F8","o","LATIN SMALL LETTER O WITH STROKE"),
    c("\u00FA","","LATIN SMALL LETTER U WITH ACUTE"),
    c("\uFB01","fi","LATIN SMALL LIGATURE FI"),
    c("\uFB02","fl","LATIN SMALL LIGATURE FL"),
    c("\u2016","","DOUBLE VERTICAL LINE"),
    c("\u2017","","DOUBLE LOW LINE"),
    c("\u2040","","FRACTION SLASH"),
    c("\u2192","","RIGHTWARDS ARROW"),
    c("\u2205","","EMPTY SET"),
    c("\u2260","","NOT EQUAL TO"),
    c("\u2264","","LESS-THAN OR EQUAL TO"),
    c("\u2500","","BOX DRAWINGS LIGHT HORIZONTAL"),
    c("\u25AA","","BLACK SMALL SQUARE"),
    c("\u25AC","","BLACK RECTANGLE"),
    c("\u263A","","WHITE SMILING FACE"),
    c("\u03B1","alpha","GREEK SMALL LETTER ALPHA")
)

# http://www.alanwood.net/unicode/emoticons.html
EMOTICONSMAP = list(
    c()
)

